# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: parity2.proto

require 'google/protobuf'


descriptor_data = "\n\rparity2.proto\x12\x07parity2\"\x8c\x02\n\x06Legacy\x12\x0f\n\x07o_int32\x18\x01 \x01(\x05\x12\x17\n\x08o_string\x18\x02 \x01(\t:\x05hello\x12\x15\n\to_default\x18\x03 \x01(\x05:\x02\x34\x32\x12\x1d\n\x06o_enum\x18\x04 \x01(\x0e\x32\r.parity2.Mode\x12\x10\n\x08o_double\x18\x05 \x01(\x01\x12\x14\n\x06o_bool\x18\x06 \x01(\x08:\x04true\x12\x0c\n\x04must\x18\x07 \x02(\x05\x12\r\n\x05\x64\x65lta\x18\x08 \x03(\x12\x12\x18\n\x0cpacked_delta\x18\t \x03(\x12\x42\x02\x10\x01\x12\x1f\n\x06nested\x18\n \x03(\x0b\x32\x0f.parity2.Legacy\x12\x0f\n\x07o_bytes\x18\x0b \x01(\x0c\x12\x11\n\to_fixed64\x18\x0c \x01(\x06*\x1d\n\x04Mode\x12\t\n\x05\x46IRST\x10\x05\x12\n\n\x06SECOND\x10\x06"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Parity2
  Legacy = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("parity2.Legacy").msgclass
  Mode = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("parity2.Mode").enummodule
end
